### PR TITLE
Updated fs-extra lib to ^0.16.0

### PR DESCRIPTION
**Pull request by thvd**

### CODE REVIEW

**Comment by kevva** [comment]
Thanks :).

**Comment by thvd** [comment]
Are you going to publish a new version of your library soon?

**Comment by kevva** [comment]
@thvd, published 1.0.6 just now!

**Comment by thvd** [comment]
@kevva, were can I find 1.0.6? Because I can't find it.

**Comment by kevva** [comment]
@thvd, sorry, thought I had updated it. Should be published now!

**Comment by thvd** [comment]
Thanks :+1:

**Pull request merged**
